language: shell
os: linux
dist: bionic
services:
  - docker

notifications:
  email: false

# Add jobs according to usage metrics:
# http://mcstats.org/global/
# https://bstats.org/global/bukkit
# Last checked: 28.05.2020
# https://github.com/D3strukt0r/docker-spigot/wiki/Server-version-usage
jobs:
  include:
    - env: SPIGOT_VERSION=latest

    # bStats: 56.8%
    # MCStats: N/A
    - if: branch = master
      env: SPIGOT_VERSION=1.15.2

    # bStats: 1.3%
    # MCStats: N/A
    - if: branch = master
      env: SPIGOT_VERSION=1.15.1

    # bStats: 0.6%
    # MCStats: N/A
    - if: branch = master
      env: SPIGOT_VERSION=1.15

    # bStats: 7.9%
    # MCStats: N/A
    - if: branch = master
      env: SPIGOT_VERSION=1.14.4

    # bStats: 1.9%
    # MCStats: N/A
    - if: branch = master
      env: SPIGOT_VERSION=1.13.2

    # bStats: 12.6%
    # MCStats: 37.5%
    - if: branch = master
      env: SPIGOT_VERSION=1.12.2

    # bStats: N/A
    # MCStats: 2.2%
    - if: branch = master
      env: SPIGOT_VERSION=1.12.1

    # bStats: N/A
    # MCStats: 4.3%
    - if: branch = master
      env: SPIGOT_VERSION=1.12

    # bStats: N/A
    # MCStats: 4.6%
    - if: branch = master
      env: SPIGOT_VERSION=1.11.2

    # bStats: N/A
    # MCStats: 0.5%
    - if: branch = master
      env: SPIGOT_VERSION=1.11

    # bStats: N/A
    # MCStats: 1.8%
    - if: branch = master
      env: SPIGOT_VERSION=1.10.2

    # bStats: N/A
    # MCStats: 0.5%
    - if: branch = master
      env: SPIGOT_VERSION=1.10

    # bStats: N/A
    # MCStats: 0.7%
    - if: branch = master
      env: SPIGOT_VERSION=1.9.4

    # bStats: 13.9%
    # MCStats: 27.5%
    - if: branch = master
      env: SPIGOT_VERSION=1.8.8

    # bStats: N/A
    # MCStats: 0.5%
    - if: branch = master
      env: SPIGOT_VERSION=1.8.7

    # bStats: 0.6%
    # MCStats: 2.9%
    - if: branch = master
      env: SPIGOT_VERSION=1.8

script:
  - ./build/travis.sh
