name: Check outdated builds

env:
  IMAGE_NAME: spigot

on:
  schedule:
    - cron: "0 * * * *" # Every hour

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        id: prep
        run: |
          echo "::set-output name=repository::$(echo "${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME" | tr '[A-Z]' '[a-z]')"
          echo "::set-output name=latestSpigotVersion::$(
            curl -s https://hub.spigotmc.org/versions/ |
            egrep "*[0-9]\.[0-9]{1,2}(\.[0-9]){0,}?(-pre[0-9]){0,}" -o |
            uniq |
            sed 's/\.$//' |
            sed 's/-pre/~pre/' |
            sort --version-sort |
            sed 's/~pre/-pre/' |
            tail -n 1
          )"

      # https://stackoverflow.com/questions/32113330/check-if-imagetag-combination-already-exists-on-docker-hub
      - name: Check if version already build
        id: docker-tag-exists
        run: |
          function docker_tag_exists() {
              TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${{ secrets.DOCKER_PASSWORD }}'", "password": "'${{ secrets.DOCKER_USERNAME }}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
              curl --silent -f --head -lL https://hub.docker.com/v2/repositories/$1/tags/$2/ >/dev/null
          }
          if docker_tag_exists "${{ steps.prep.outputs.repository }}" "${{ steps.prep.outputs.latestSpigotVersion }}"; then
              echo "::set-output name=exists::true"
          else
              echo "::set-output name=exists::false"
          fi

      - name: Check if outdated
        id: check-if-outdated
        if: steps.docker-tag-exists.outputs.exists == 'true'
        run: |
          echo "Starting Spigot..."
          docker pull ${{ steps.prep.outputs.repository }}:${{ steps.prep.outputs.latestSpigotVersion }}
          docker run -i --rm --name spigot -e JAVA_OPTIONS=-Xmx4G ${{ steps.prep.outputs.repository }}:${{ steps.prep.outputs.latestSpigotVersion }} 2>&1 | tee output.txt || true
          sleep 3

          echo "Killing process..."
          docker stop spigot || true
          docker rm spigot || true

          # https://stackoverflow.com/questions/11287861/how-to-check-if-a-file-contains-a-specific-string-using-bash
          if grep -q outdated output.txt; then
              echo "::set-output name=outdated::true"
          else
              echo "::set-output name=outdated::false"
          fi

        # https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
      - name: Start build workflow
        if: steps.docker-tag-exists.outputs.exists == 'false' || steps.check-if-outdated.outputs.outdated == 'true'
        run: |
          curl \
              --silent \
              --request POST \
              --header "Authorization: Bearer ${{ secrets.PAT }}" \
              --header "Accept: application/vnd.github.v3+json" \
              --url https://api.github.com/repos/D3strukt0r/docker-spigot/actions/workflows/ci-cd.yml/dispatches \
              --data "{\"ref\":\"refs/heads/master\",\"inputs\":{\"version\":\"${{ steps.prep.outputs.latestSpigotVersion }}\"}}"
          curl \
              --silent \
              --request POST \
              --header "Authorization: Bearer ${{ secrets.PAT }}" \
              --header "Accept: application/vnd.github.v3+json" \
              --url https://api.github.com/repos/D3strukt0r/docker-spigot/actions/workflows/ci-cd.yml/dispatches \
              --data "{\"ref\":\"refs/heads/master\",\"inputs\":{\"version\":\"latest\"}}"
