name: Labeler

on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # The path to the label configuration file
          # configuration-path: .github/labeler.yml # optional, default is ".github/labeler.yml"
          # Whether or not to remove labels when matching files are reverted or no longer changed by the PR
          sync-labels: true # optional, default is "false"
